# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Crypt-Polybius`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.008"^^:CpanId ];
	:runtime-requirement    [ :on "Moo 1.002000"^^:CpanId ];
	:runtime-requirement    [ :on "Text::Unidecode"^^:CpanId ];
	.

